import 'package:flutter/material.dart';


const tWelcomeTitle = "Hope you a nice weather";
const tWelcomesSubtitle ="";
const tLogin = "Login";
const tSignUp = "SignUp";
const tFetch ="Fetching location...";
const tErrorSer ="Location services are disabled.";
const tLPD = "Location permissions are denied.";
const tLPPD = "Location permissions are permanently denied.";
const tErrorF ="Error fetching location.";
const overcast_clouds = "overcast clouds";
const broken_clouds="broken clouds";
const scattered_clouds = "scattered clouds";
const few_clouds ="few clouds";
const mist = "mist";
const clear = "Clear";
const sunny = "Sunny";
const clear_sky ="clear sky";
const heavy_rain = "Heavy Rain";
const rain= "Rain";
const showers = "Showers";
const moderate_rain = "moderate rain";
const light_rain = "light rain";
const  heavy_snow= "heavy snow";
const  shower_snow= "shower snow";
const shower_sleet = "shower sleet";
const light_snow = "light snow";
const not_authenticated = "Not authenticated";
const fDw = "Fetching weather data...";
const fLoad = "Failed to load weather data:";